---
- name: Create aws vpc, ecs, ecr
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    project_path: "{{ terraform_dir }}"
    state: present 
    lock: yes
    backend_config:
      region: "us-east-1"
      bucket: "awsecs-terraform-remote-state"
      key: "vpc-n-ecs-terraform.tfstate"
      dynamodb_table:  "vpc-n-ecs-terraform-remote-lock"
      encrypt: "true"
    force_init: true
  register: terraform_run
