---
- name: Copy vault bin file to home bin dir
  copy:
    src: "{{ item[0] }}{{ item[1] }}"
    dest: "{{ user_home_bin }}/{{ item[1] }}"
    owner: "{{ user_home.split('/')[-1] }}"
    group: "{{ user_home.split('/')[-1] }}"
    mode: '0755'
  with_nested:
    - "{{ pkgs.vault.download_dir }}"
    - "{{ pkgs.vault.bin_files }}"

- name: Copy terraform bin file to home bin dir
  copy:
    src: "{{ item[0] }}{{ item[1] }}"
    dest: "{{ user_home_bin }}/{{ item[1] }}"
    owner: "{{ user_home.split('/')[-1] }}"
    group: "{{ user_home.split('/')[-1] }}"
    mode: '0755'
  with_nested:
    - "{{ pkgs.terraform.download_dir }}"
    - "{{ pkgs.terraform.bin_files }}"

- name: Copy jq bin file to home bin dir
  copy:
    src: "{{ item[0] }}{{ item[1] }}"
    dest: "{{ user_home_bin }}/jq"
    owner: "{{ user_home.split('/')[-1] }}"
    group: "{{ user_home.split('/')[-1] }}"
    mode: '0755'
  with_nested:
    - "{{ pkgs.jq.download_dir }}"
    - "{{ pkgs.jq.bin_files }}"

- name: Delete download tmp dir
  file:
    path: /tmp/download
    state: absent
