---
- hosts: localhost
  roles:
    - { role: management-prerequisite-cli,  tags: prepare_management_server, become: yes }
    - { role: vpc-ecs-n-ecr-environment-remote-state, tags: first_time_run }
    - { role: vpc-ecs-n-ecr-environment }
