---
- name: Create S3 remote state bucket and vpc-n-eks dynamoDB lock table
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    project_path: "{{ terraform_dir }}"
    state: present 
    force_init: true
  register: terraform_run
